In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

# scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
encoder= LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [10]:
X_train

array([[-0.82398511, -1.44908753, -0.83330405, ..., -0.43610674,
        -0.28688209, -0.2276261 ],
       [-0.36559644, -0.83556614, -0.34066657, ..., -0.22401819,
        -1.44293278, -0.71031974],
       [ 2.55663131,  0.11700653,  2.48711414, ...,  1.63847771,
        -0.01125693, -0.62942136],
       ...,
       [ 0.59988469,  0.58983316,  0.63296801, ..., -0.17921075,
        -0.28215709, -0.26483935],
       [ 0.12144151,  0.77435087,  0.17109439, ..., -0.09258304,
        -1.03500754, -0.2373339 ],
       [ 1.43357907,  1.2633228 ,  1.66813031, ...,  0.8961678 ,
         0.41084332,  0.96319798]])

In [11]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1])

In [13]:
type(y_train)

numpy.ndarray

In [14]:
type(y_test)

numpy.ndarray

# Numpy Array to tensor

In [15]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

# Defining the model

In [18]:
X_train.shape[1]

30

In [26]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z= torch.matmul(X, self.weights) + self.bias
    y_pred= torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon= 1e-7
    y_pred= torch.clamp(y_pred, epsilon, 1-epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [22]:
model= MySimpleNN(X_train_tensor)

In [23]:
model.weights

tensor([[0.0684],
        [0.2506],
        [0.4480],
        [0.3433],
        [0.9725],
        [0.5391],
        [0.0703],
        [0.6412],
        [0.6364],
        [0.8021],
        [0.2407],
        [0.2012],
        [0.1669],
        [0.9471],
        [0.9162],
        [0.6303],
        [0.4412],
        [0.5564],
        [0.5539],
        [0.9601],
        [0.0257],
        [0.2773],
        [0.6222],
        [0.1978],
        [0.3453],
        [0.2211],
        [0.2084],
        [0.2066],
        [0.0520],
        [0.6485]], dtype=torch.float64, requires_grad=True)

In [24]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

# parameters

In [27]:
learning_rate=0.1
epochs= 25

# Training pipeline

In [31]:
# create model
model = MySimpleNN(X_train_tensor)


# define loop
for epoch in range(epochs):


  # forward pass
  y_pred = model.forward(X_train_tensor)


  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)


  # backward pass
  loss.backward()


  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad


  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()


  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 4.320242893731454
Epoch: 2, Loss: 4.231289528245988
Epoch: 3, Loss: 4.136368649886126
Epoch: 4, Loss: 4.031888051212135
Epoch: 5, Loss: 3.922667023838265
Epoch: 6, Loss: 3.8101448879838067
Epoch: 7, Loss: 3.693572178457744
Epoch: 8, Loss: 3.5708062511927863
Epoch: 9, Loss: 3.4422834118258288
Epoch: 10, Loss: 3.306397930496697
Epoch: 11, Loss: 3.1708731239151664
Epoch: 12, Loss: 3.033658394936432
Epoch: 13, Loss: 2.8905769560841805
Epoch: 14, Loss: 2.7430406535286354
Epoch: 15, Loss: 2.594849575332631
Epoch: 16, Loss: 2.4458106892338636
Epoch: 17, Loss: 2.2928787189992126
Epoch: 18, Loss: 2.1403314369024455
Epoch: 19, Loss: 1.990250147540865
Epoch: 20, Loss: 1.8448348977878462
Epoch: 21, Loss: 1.7039772927595978
Epoch: 22, Loss: 1.5667019553132773
Epoch: 23, Loss: 1.4413375392332504
Epoch: 24, Loss: 1.3290159521342715
Epoch: 25, Loss: 1.2289813733363733

In [32]:
model.bias

tensor([-0.0695], dtype=torch.float64, requires_grad=True)

# Evaluation

In [33]:
y_pred= model.forward(X_test_tensor)

In [34]:
y_pred

tensor([[0.9666],
        [0.3808],
        [0.3259],
        [0.2992],
        [0.0352],
        [0.4726],
        [0.8035],
        [0.3276],
        [0.1733],
        [0.0645],
        [0.1112],
        [0.7113],
        [0.1760],
        [0.9509],
        [0.2596],
        [0.8480],
        [0.3527],
        [0.9398],
        [0.5653],
        [0.1414],
        [0.8958],
        [0.6798],
        [0.8988],
        [0.1513],
        [0.5045],
        [0.0993],
        [0.6468],
        [0.0742],
        [0.2155],
        [0.5601],
        [0.4983],
        [0.1997],
        [0.0700],
        [0.0557],
        [0.1863],
        [0.8179],
        [0.6393],
        [0.1882],
        [0.0313],
        [0.6407],
        [0.2226],
        [0.3722],
        [0.1041],
        [0.5766],
        [0.6145],
        [0.5975],
        [0.9569],
        [0.1128],
        [0.1832],
        [0.1404],
        [0.2265],
        [0.8739],
        [0.3160],
        [0.2938],
        [0.4670],
        [0.9813],
        [0.0166],
        [0.7311],
        [0.3457],
        [0.5057],
        [0.7587],
        [0.1062],
        [0.7140],
        [0.0210],
        [0.4301],
        [0.9655],
        [0.1124],
        [0.0403],
        [0.2366],
        [0.0817],
        [0.4859],
        [0.2282],
        [0.7368],
        [0.8969],
        [0.7525],
        [0.0932],
        [0.3077],
        [0.6682],
        [0.1720],
        [0.0784],
        [0.2145],
        [0.0780],
        [0.8999],
        [0.2616],
        [0.0497],
        [0.5515],
        [0.4772],
        [0.3174],
        [0.0920],
        [0.3737],
        [0.3180],
        [0.0870],
        [0.1673],
        [0.1098],
        [0.9861],
        [0.2181],
        [0.0223],
        [0.8552],
        [0.0415],
        [0.1105],
        [0.6828],
        [0.7388],
        [0.4809],
        [0.8938],
        [0.7907],
        [0.4990],
        [0.1497],
        [0.5360],
        [0.1347],
        [0.9991],
        [0.9748],
        [0.4223],
        [0.3202],
        [0.3852]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)

In [35]:
y_pred> 0.9

tensor([[ True],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [False],
        [False],
        [False],
        [ True],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [ True],
        [ True],
        [False],
        [False],
        [False]])

In [38]:
y_pred= (y_pred> 0.9).float()

In [40]:
accuracy= (y_pred == y_test_tensor).float().mean()

In [41]:
accuracy

tensor(0.6108)

In [42]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6108033061027527